"""Synthetic validators for the D2-T08 D3 handoff boundary."""

from __future__ import annotations

from typing import Any


class D2AcceptanceD3HandoffValidationError(ValueError):
    """Raised when a synthetic D2-T08 handoff payload violates the contract."""


REQUIRED_COMPONENT_REFS = {
    "raw_price_ref",
    "adjusted_price_ref",
    "trading_constraint_ref",
    "market_price_quality_ref",
    "mechanical_gap_ref",
    "pcvt_input_readiness_ref",
    "membership_ref",
    "calendar_ref",
    "source_snapshot_ref",
    "run_ref",
}
REQUIRED_FACT_GROUPS = {
    "identity",
    "raw_trading_facts",
    "continuous_research_prices",
    "trading_constraints",
    "market_quality_flags",
    "mechanical_gap_attribution",
    "pcvt_input_readiness",
    "membership_alignment",
    "calendar_alignment",
    "source_lineage",
    "observed_at_revision",
}
FUTURE_FIELDS = {
    "future_return",
    "future_max_return",
    "label",
    "breakout_direction",
    "outcome",
    "target",
    "holding_period_return",
    "backtest_signal",
    "portfolio_return",
}
ROW_PAYLOAD_FIELDS = {
    "raw_rows",
    "qfq_rows",
    "hfq_rows",
    "price_rows",
    "row_level_prices",
    "vendor_payload",
    "raw_vendor_payload",
}
PARTIAL_READINESS = {
    "partial_pending_amount_volume_unit_validation_and_adjusted_vwap_policy",
    "partial_pending_volume_unit_validation_and_adjusted_volume_policy",
}


def _as_set(payload: dict[str, Any], field: str) -> set[str]:
    value = payload.get(field)
    if not isinstance(value, list):
        raise D2AcceptanceD3HandoffValidationError(f"{field} must be a list")
    return {str(item) for item in value}


def validate_d3_component_refs(payload: dict[str, Any]) -> None:
    refs = _as_set(payload, "component_refs")
    missing = sorted(REQUIRED_COMPONENT_REFS - refs)
    if missing:
        raise D2AcceptanceD3HandoffValidationError(
            f"missing D3 component refs: {missing}"
        )
    if not payload.get("source_snapshot_id"):
        raise D2AcceptanceD3HandoffValidationError("missing source_snapshot_id")


def validate_d3_required_fact_groups(payload: dict[str, Any]) -> None:
    fact_groups = _as_set(payload, "fact_groups")
    missing = sorted(REQUIRED_FACT_GROUPS - fact_groups)
    if missing:
        raise D2AcceptanceD3HandoffValidationError(f"missing D3 fact groups: {missing}")


def validate_observed_at_revision_policy(payload: dict[str, Any]) -> None:
    if not payload.get("observed_at"):
        raise D2AcceptanceD3HandoffValidationError("missing observed_at")
    if payload.get("history_revision_class") == "final_revised_history" and payload.get(
        "formal_point_in_time_supported"
    ):
        raise D2AcceptanceD3HandoffValidationError(
            "final revised history cannot claim point-in-time support"
        )
    if payload.get("factor_as_of_time_coverage") == "fail" and payload.get(
        "formal_continuous_price_ready"
    ):
        raise D2AcceptanceD3HandoffValidationError(
            "factor_as_of_time coverage fail blocks formal readiness"
        )
    if payload.get("revision_timestamp_coverage") == "fail" and payload.get(
        "revision_aware_ready"
    ):
        raise D2AcceptanceD3HandoffValidationError(
            "revision timestamp coverage fail blocks revision-aware readiness"
        )


def validate_no_future_information(payload: dict[str, Any]) -> None:
    forbidden = sorted(FUTURE_FIELDS & set(payload))
    if forbidden:
        raise D2AcceptanceD3HandoffValidationError(
            f"future outcome fields are prohibited: {forbidden}"
        )


def validate_no_d1_d2_bypass(payload: dict[str, Any]) -> None:
    allowed_sources = payload.get("r0_allowed_sources", [])
    if not isinstance(allowed_sources, list):
        raise D2AcceptanceD3HandoffValidationError("r0_allowed_sources must be a list")
    for source in allowed_sources:
        source_name = str(source)
        if source_name.startswith(("d1.", "d2.")):
            raise D2AcceptanceD3HandoffValidationError(
                "R0 must not bypass D3 into D1/D2"
            )
    if "d3.daily_market_observations" not in {str(item) for item in allowed_sources}:
        raise D2AcceptanceD3HandoffValidationError(
            "R0 must read the D3 daily observation boundary"
        )


def validate_pcvt_handoff_policy(payload: dict[str, Any]) -> None:
    if payload.get("pcvt_values_generated"):
        raise D2AcceptanceD3HandoffValidationError("PCVT values generated by D2-T08")
    if payload.get("r0_thresholds_defined"):
        raise D2AcceptanceD3HandoffValidationError("R0 thresholds defined by D2-T08")
    if payload.get("pcvt_candidate_set_status") != "proposed_not_r0_finalized":
        raise D2AcceptanceD3HandoffValidationError("PCVT candidate set finalized")
    readiness = payload.get("pcvt_readiness", {})
    if not isinstance(readiness, dict):
        raise D2AcceptanceD3HandoffValidationError("pcvt_readiness must be an object")
    for indicator_id in ["C2_AdjVWAPSpread_5_60", "V1_VolShrink20_60"]:
        if readiness.get(indicator_id) not in PARTIAL_READINESS:
            raise D2AcceptanceD3HandoffValidationError(
                f"{indicator_id} partial readiness missing"
            )


def validate_d2_acceptance_flags(payload: dict[str, Any]) -> None:
    for field in [
        "formal_ingestion_authorized",
        "d3_generated",
        "r0_generated",
    ]:
        if payload.get(field):
            raise D2AcceptanceD3HandoffValidationError(f"{field} must be false")


def validate_no_row_level_payload(payload: dict[str, Any]) -> None:
    forbidden = sorted(ROW_PAYLOAD_FIELDS & set(payload))
    if forbidden:
        raise D2AcceptanceD3HandoffValidationError(
            f"row-level payload fields are prohibited: {forbidden}"
        )


def validate_d2_acceptance_d3_handoff(payload: dict[str, Any]) -> None:
    validate_no_future_information(payload)
    validate_no_row_level_payload(payload)
    validate_d2_acceptance_flags(payload)
    validate_d3_component_refs(payload)
    validate_d3_required_fact_groups(payload)
    validate_observed_at_revision_policy(payload)
    validate_no_d1_d2_bypass(payload)
    validate_pcvt_handoff_policy(payload)
